// Use of this source code is governed by a MIT license that can be found in the LICENSE file.
// sms10086@hotmail.com

/* Generated by ffmpeg configure */

package goffmpeg6


const AV_HAVE_BIGENDIAN = 0
const AV_HAVE_FAST_UNALIGNED = 1

                         
                         


                              
